
CREATE PROCEDURE "NKI_ERP_PRD"._USP_GETCOUNTMASTERDATA(in DTYPE NVARCHAR(10),in STATUS INT)
AS
	
BEGIN
	IF :DType='OITM' THEN	
		IF STATUS = 1 THEN
			SELECT COUNT(*) As CountMaster FROM "NKI_ERP_PRD"."OITM" OI
			WHERE LEFT(OI."ItemCode",1) IN('A','B','D') AND  OI."ItemCode" NOT IN(SELECT "ENTRY" FROM "NKI_ERP_PRD"."_UST_MASTERDATA" WHERE "TYPE" IN(DType));
		ELSE 
			SELECT COUNT(*) As CountMaster FROM "NKI_ERP_PRD"."OITM" OI
			WHERE LEFT(OI."ItemCode",1) IN('A','B','D') AND OI."ItemCode" IN(SELECT "ENTRY" FROM "NKI_ERP_PRD"."_UST_MASTERDATA" WHERE "STATUS" IN(1) AND "TYPE" IN(DType));
		END IF;	
	ELSE IF :DType='OITB' THEN
		IF STATUS =1 THEN
			SELECT COUNT(*) As CountMaster FROM "NKI_ERP_PRD"."OITB" 
			WHERE "ItmsGrpCod" NOT IN(SELECT "ENTRY" FROM "NKI_ERP_PRD"."_UST_MASTERDATA" WHERE "TYPE" IN(DType));
		ElSE 
			SELECT COUNT(*) As CountMaster FROM "NKI_ERP_PRD"."OITB" 
			WHERE "ItmsGrpCod" IN(SELECT "ENTRY" FROM "NKI_ERP_PRD"."_UST_MASTERDATA" WHERE "STATUS" IN(1) AND "TYPE" IN(DType));
		END IF;
	ELSE IF :DType='OHEM' THEN
		IF STATUS =1 THEN
			SELECT COUNT(*) As CountMaster FROM "NKI_ERP_PRD"."OHEM" OH 
			WHERE OH."ExtEmpNo" NOT IN(SELECT "ENTRY" FROM "NKI_ERP_PRD"."_UST_MASTERDATA" WHERE "TYPE" IN(DType));
		ELSE
			SELECT COUNT(*) As CountMaster FROM "NKI_ERP_PRD"."OHEM" OH 
			WHERE OH."ExtEmpNo" IN(SELECT "ENTRY" FROM "NKI_ERP_PRD"."_UST_MASTERDATA" WHERE "STATUS" IN(1) AND "TYPE" IN(DType));
		END IF;
	ELSE IF :DType='OHPS' THEN
		IF STATUS =1 THEN
			SELECT COUNT(*) As CountMaster FROM "NKI_ERP_PRD"."OHPS" 
			WHERE SUBSTR_BEFORE("descriptio",'-') NOT IN(SELECT "ENTRY" FROM "NKI_ERP_PRD"."_UST_MASTERDATA" WHERE "TYPE" IN(DType));
		ELSE
			SELECT COUNT(*) As CountMaster FROM "NKI_ERP_PRD"."OHPS" 
			WHERE SUBSTR_BEFORE("descriptio",'-') IN(SELECT "ENTRY" FROM "NKI_ERP_PRD"."_UST_MASTERDATA" WHERE "STATUS" IN(1) AND "TYPE" IN(DType));
		END IF;
	ELSE IF :DType='OUDP' THEN
		IF STATUS =1 THEN
			SELECT COUNT(*) As CountMaster FROM "NKI_ERP_PRD"."OUDP" 
			WHERE "Code" > 0 AND LEFT("Remarks",2) NOT IN(SELECT "ENTRY" FROM "NKI_ERP_PRD"."_UST_MASTERDATA" WHERE "TYPE" IN(DType));
		ELSE
			SELECT COUNT(*) As CountMaster FROM "NKI_ERP_PRD"."OUDP" 
			WHERE "Code" > 0 AND LEFT("Remarks",2) IN(SELECT "ENTRY" FROM "NKI_ERP_PRD"."_UST_MASTERDATA" WHERE "STATUS" IN(1) AND "TYPE" IN(DType));
		END IF;
	ELSE IF :DType='OUBR' THEN
		IF STATUS =1 THEN
			SELECT COUNT(*) As CountMaster FROM "NKI_ERP_PRD"."OUBR" 
			WHERE "Code" > 0 AND "Remarks" NOT IN(SELECT "ENTRY" FROM "NKI_ERP_PRD"."_UST_MASTERDATA" WHERE "TYPE" IN(DType));
		ELSE
			SELECT COUNT(*) As CountMaster FROM "NKI_ERP_PRD"."OUBR" 
			WHERE "Code" > 0 AND "Remarks" IN(SELECT "ENTRY" FROM "NKI_ERP_PRD"."_UST_MASTERDATA" WHERE "STATUS" IN(1) AND "TYPE" IN(DType));
		END IF;
	ELSE IF :DType='OPRC' THEN
		IF STATUS =1 THEN
			SELECT COUNT(*) As CountMaster FROM "NKI_ERP_PRD"."OPRC" 
			WHERE "Locked"= 'N' AND "DimCode"='3' AND "PrcCode" NOT IN(SELECT "ENTRY" FROM "NKI_ERP_PRD"."_UST_MASTERDATA" WHERE "TYPE" IN(DType));
		ELSE
			SELECT COUNT(*) As CountMaster FROM "NKI_ERP_PRD"."OPRC" 
			WHERE "Locked"= 'N' AND "DimCode"='3' AND "PrcCode" IN(SELECT "ENTRY" FROM "NKI_ERP_PRD"."_UST_MASTERDATA" WHERE "STATUS" IN(1) AND "TYPE" IN(DType));
		END IF;
	ELSE IF :DType='OCRD1' THEN
		IF STATUS =1 THEN
			SELECT COUNT(*) As CountMaster FROM "NKI_ERP_PRD"."OCRD"
			WHERE "CardType"= 'C' AND LEFT("CardCode",4) IN('CL01','CL02','CL03') AND "CardCode" NOT IN('CL01-99999','CL02-99999') 
			AND "CardCode" NOT IN(SELECT "ENTRY" FROM "NKI_ERP_PRD"."_UST_MASTERDATA" WHERE "TYPE" IN(DType));
		ELSE
			SELECT COUNT(*) As CountMaster FROM "NKI_ERP_PRD"."OCRD"
			WHERE "CardType"= 'C' AND LEFT("CardCode",4) IN('CL01','CL02','CL03') AND "CardCode" NOT IN('CL01-99999','CL02-99999') 
			AND "CardCode" IN(SELECT "ENTRY" FROM "NKI_ERP_PRD"."_UST_MASTERDATA" WHERE "STATUS" IN(1) AND "TYPE" IN(DType));
		END IF;
	ELSE IF :DType='OCRD2' THEN
		IF STATUS =1 THEN
			SELECT COUNT(*) As CountMaster FROM "NKI_ERP_PRD"."OCRD"
			WHERE "CardType"= 'S' AND "CardCode" NOT IN('VL01-99999','VL02-99999','VL03-99999','VL04-99999','VL05-99999','VL06-99999','VL07-99999','VL08-99999','VL09-99999')  
			AND "CardCode" NOT IN(SELECT "ENTRY" FROM "NKI_ERP_PRD"."_UST_MASTERDATA" WHERE "TYPE" IN(DType));
		ELSE
			SELECT COUNT(*) As CountMaster FROM "NKI_ERP_PRD"."OCRD"
			WHERE "CardType"= 'S' AND "CardCode" NOT IN('VL01-99999','VL02-99999','VL03-99999','VL04-99999','VL05-99999','VL06-99999','VL07-99999','VL08-99999','VL09-99999') 
			AND "CardCode" IN(SELECT "ENTRY" FROM "NKI_ERP_PRD"."_UST_MASTERDATA" WHERE "STATUS" IN(1) AND "TYPE" IN(DType));
		END IF;
	ELSE
	
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
	END IF;
END;
